from playwright.sync_api import sync_playwright
import pathlib
base=pathlib.Path('/home/user/site')
with sync_playwright() as p:
    b=p.chromium.launch()
    d=b.new_page(viewport={'width':1440,'height':1000})
    d.goto((base/'index.html').as_uri(), wait_until="load"); d.wait_for_timeout(1500)
    ow=d.evaluate("document.documentElement.scrollWidth"); iw=d.evaluate("window.innerWidth")
    print("HOME horizontal overflow:", ow-iw, "px  (0 = fixed)")
    d.screenshot(path="shots/f-home.jpg", quality=74, type="jpeg")
    d.mouse.wheel(0,1250); d.wait_for_timeout(1200)
    d.screenshot(path="shots/f-home2.jpg", quality=74, type="jpeg")
    d.goto((base/'cleveland-browns-shirts/index.html').as_uri(), wait_until="load"); d.wait_for_timeout(1200)
    print("COLLECTION overflow:", d.evaluate("document.documentElement.scrollWidth-window.innerWidth"))
    d.mouse.wheel(0,780); d.wait_for_timeout(1200)
    d.screenshot(path="shots/f-col.jpg", quality=74, type="jpeg")
    d.goto((base/'shop/sanders-13-special-edition/index.html').as_uri(), wait_until="load"); d.wait_for_timeout(1300)
    print("PDP overflow:", d.evaluate("document.documentElement.scrollWidth-window.innerWidth"))
    d.screenshot(path="shots/f-pdp.jpg", quality=74, type="jpeg")
    m=b.new_page(viewport={'width':390,'height':844},device_scale_factor=2)
    m.goto((base/'cleveland-browns-shirts/index.html').as_uri(), wait_until="load"); m.wait_for_timeout(1200)
    print("MOBILE overflow:", m.evaluate("document.documentElement.scrollWidth-window.innerWidth"))
    m.mouse.wheel(0,700); m.wait_for_timeout(1000)
    m.screenshot(path="shots/f-mob.jpg", quality=74, type="jpeg")
    b.close()
