# Human-verified catalog facts: read off the real design artwork.
# name = SEO H1 / product name, art = text printed on the garment,
# kw = extra long-tail keywords, type = garment override (auto-detected otherwise)
CATALOG = {
  "new-era-crewneck": dict(name="Cleveland New Era Crewneck", art="NEW ERA with EST. 1946",
    kw=["cleveland new era crewneck", "browns new era sweatshirt", "cleveland quarterback shirt",
        "browns opening day crewneck", "dawg pound sweatshirt", "north coast crewneck",
        "est 1946 browns shirt", "cleveland football gift"], theme="classic"),
"let-it-rip": dict(name="Cleveland Let It Rip Tee", art="LET IT RIP",
    kw=["cleveland let it rip tee", "browns let it rip shirt", "cleveland quarterback tee",
        "browns opening day shirt", "dawg pound tee", "cleveland gameday tee",
        "cleveland football gift"], theme="city"),
"sanders-the-next-level": dict(name="Shedeur Sanders The Next Level Shirt", art="SANDERS - THE NEXT LEVEL",
    kw=["shedeur sanders shirt", "sanders next level tee", "cleveland quarterback shirt",
        "browns rookie qb shirt", "sanders 12 browns tee", "cleveland football gift"], theme="player"),
"limited-edition-m-vs-all": dict(name="Michigan M Vs All Tee", art="M -VS- ALL with the Michigan M",
    kw=["michigan vs all shirt", "michigan m vs all tee", "go blue vs everybody shirt",
        "michigan rivalry tee", "ann arbor football shirt", "wolverines fan gear",
        "michigan football gift"], theme="classic"),
"limited-edition-qb19": dict(name="Michigan QB19 Tee", art="QB 19",
    kw=["michigan qb19 shirt", "michigan quarterback 19 tee", "go blue quarterback shirt",
        "michigan football tee", "ann arbor quarterback gift", "wolverines qb shirt"],
    theme="player"),
"all-we-want-all-we-got-25": dict(name="Cleveland Under Dawgs Playoffs Shirt", art="THE CLEVELAND UNDER DAWGS - ALL WE GOT, ALL WE NEED - PLAYOFFS", kw=["cleveland underdogs shirt","dawg pound playoff shirt","browns playoff tee"], theme="playoff"),
"sanders-13-special-edition": dict(name="Shedeur Sanders 12 They Forgot Who I Am Shirt", art="THEY FORGOT WHO I AM - SANDERS SHEDEUR - BROWNS 12", kw=["shedeur sanders shirt","sanders browns qb tee","cleveland quarterback 12 shirt"], theme="player"),
"bend-football-fans": dict(name="Bend & Snap Funny Football Shirt", art="BEND & SNAP with vintage football", kw=["funny football shirt","bend and snap tee","football humor shirt"], theme="funny"),
"sanders-12-special-edition": dict(name="Sanders QB 12 Signature Shirt", art="SANDERS QB 12 with signature", kw=["sanders qb shirt","browns 12 quarterback tee","cleveland rookie qb shirt"], theme="player"),
"sanders-special-edition": dict(name="Sanders QB Signature White Shirt", art="SANDERS QB 12 signature, white colorway", kw=["sanders white tee","browns quarterback shirt","cleveland qb signature tee"], theme="player"),
"limited-edition-flacco-15": dict(name="Joe Flacco 15 Cleveland Shirt", art="BROWNS FLACCO 15 CLEVELAND with signature", kw=["joe flacco shirt","flacco 15 tee","cleveland flacco jersey shirt"], theme="player"),
"cleveland-its-not-that-bad-have-a-beer": dict(name="Cleveland It's Not That Bad Have A Beer Shirt", art="CLEVELAND, IT'S NOT THAT BAD. HAVE A BEER!", kw=["funny cleveland shirt","cleveland beer tee","ohio humor shirt"], theme="funny"),
"denzel": dict(name="Denzel Ward Make Them Know Your Name Shirt", art="MAKE THEM KNOW YOUR NAME - DENZEL WARD 21 - BROWNS", kw=["denzel ward shirt","browns 21 tee","cleveland cornerback shirt"], theme="player"),
"limited-edition-br-summer-2024": dict(name="Cleveland Summer Slam Shirt", art="SUMMER SLAM CLEVELAND with bulldog", kw=["cleveland summer shirt","browns summer tee","dawg pound summer shirt"], theme="classic"),
"ohio-cleveland-fans": dict(name="Ohio Football Cleveland State Outline Shirt", art="OHIO, FOOTBALL - CLEVELAND inside Ohio state map", kw=["ohio football shirt","cleveland ohio tee","ohio state outline shirt"], theme="city"),
"all-we-want-all-we-got": dict(name="Cleveland Under Dawgs All We Got Shirt", art="THE CLEVELAND UNDER DAWGS - ALL WE GOT ALL WE NEED - 2023 2024 PLAYOFFS", kw=["browns underdog shirt","dawg pound tee","cleveland playoffs shirt"], theme="playoff"),
"playoffs-never-giveup": dict(name="Playoffs Never Give Up Dawg Shirt", art="PLAYOFFS NEVER GIVE UP with bulldog", kw=["browns playoff shirt","never give up football tee","dawg pound playoffs"], theme="playoff"),
"beware-of-dawg": dict(name="Beware Of Dawg Cleveland Shirt", art="BEWARE OF DAWG with bulldog and stripes", kw=["beware of dawg shirt","dawg pound tee","cleveland bulldog shirt"], theme="classic"),
"lets-go-cleveland": dict(name="Let's Go Cleveland Football Shirt", art="LET'S GO CLEVELAND with football", kw=["lets go cleveland shirt","cleveland gameday tee","cleveland football shirt"], theme="city"),
"this-girl-loves-browns-coach": dict(name="This Girl Loves Browns' Coach Hoodie", art="THIS GIRL LOVES BROWNS' COACH with thumbs", kw=["browns coach hoodie","womens cleveland hoodie","football girlfriend gift"], theme="funny"),
"run-the-ball": dict(name="Run The Ball Kevin White Hoodie", art="RUN THE BALL KEVIN!", kw=["run the ball kevin","browns coach hoodie","funny cleveland hoodie"], theme="funny"),
"run-the-ball-kev": dict(name="Run The Ball Kevin Black Hoodie", art="RUN THE BALL KEVIN!", kw=["run the ball kevin hoodie","cleveland fan hoodie","funny football hoodie"], theme="funny"),
"she-loves-flacco": dict(name="She Loves Joe Flacco Shirt", art="SHE LOVES JOE FLACCO", kw=["she loves flacco shirt","joe flacco womens tee","flacco fan shirt"], theme="player"),
"she-love-coach-kevin": dict(name="She Loves Coach Kevin Shirt", art="SHE LOVES COACH KEVIN", kw=["coach kevin shirt","cleveland coach tee","funny browns shirt"], theme="funny"),
"she-love-coach-stefanski": dict(name="She Loves Coach Stefanski Shirt", art="SHE LOVES COACH STEFANSKI", kw=["stefanski shirt","cleveland coach tee","browns coach gift"], theme="funny"),
"flacco-fever-white": dict(name="Flacco Fever White Shirt", art="FLACCO FEVER! with helmet", kw=["flacco fever shirt","joe flacco white tee","cleveland qb shirt"], theme="player"),
"flacco-fever": dict(name="Flacco Fever Black Shirt", art="FLACCO FEVER! with helmet", kw=["flacco fever tee","joe flacco black shirt","browns qb fan shirt"], theme="player"),
"my-heart-is-on-that-field": dict(name="My Heart Is On That Field Football Shirt", art="MY HEART IS ON THAT FIELD with heartbeat football", kw=["football mom shirt","my heart is on that field","football wife tee"], theme="family"),
"dawg-pound": dict(name="Cleveland Browns Dawg Pound Shirt", art="CLEVELAND BROWNS DAWG POUND script", kw=["dawg pound shirt","cleveland dawg pound tee","browns fan shirt"], theme="classic"),
"play-off-pound-shirt": dict(name="Playoff Pound And Determined Shirt", art="PLAYOFF POUND AND DETERMINED 2023 2024 CLEVELAND", kw=["browns playoff shirt","dawg pound playoff tee","cleveland determined shirt"], theme="playoff"),
"whispered-go-browns": dict(name="So I Whispered Go Browns Funny Shirt", art="SHE ASKED ME TO TELL HER TWO WORDS EVERY GIRL WANTS TO HEAR SO I WHISPERED GO BROWNS", kw=["funny browns shirt","go browns tee","cleveland funny gift"], theme="funny"),
"flacco-round-and-find-out": dict(name="Flacco 'Round And Find Out Shirt", art="FLACCO 'ROUND AND FIND OUT - STILL ELITE - 15", kw=["flacco round and find out","joe flacco still elite","browns 15 shirt"], theme="player"),
"winter-hat-beanie-go-browns": dict(name="Go Browns Orange Winter Beanie", art="GO BROWNS embroidered-look knit beanie", kw=["browns beanie","cleveland winter hat","go browns knit hat"], theme="classic", type="Beanie"),
"limited-edition-24n157": dict(name="Go Browns Player Hoodie", art="GO BROWNS with player photo", kw=["go browns hoodie","cleveland player hoodie","browns fan sweatshirt"], theme="player"),
"limited-edition-lfg": dict(name="LFG CLE Cleveland Sweatshirt", art="LFG CLE", kw=["lfg cle shirt","cleveland sweatshirt","browns gameday crewneck"], theme="city"),
"limited-edition-br95": dict(name="Browns Myles Garrett 95 Shirt", art="BROWNS MYLES GARRETT 95", kw=["myles garrett shirt","browns 95 tee","garrett defensive player shirt"], theme="player"),
"limited-edition-br951": dict(name="Myles Garrett 95 Browns Hoodie", art="BROWNS MYLES GARRETT 95", kw=["myles garrett hoodie","browns 95 sweatshirt","cleveland defense hoodie"], theme="player"),
"limited-edition-stefanski": dict(name="Coach Stefanski Cleveland Sweatshirt", art="COACH BROWNS STEFANSKI CLEVELAND", kw=["stefanski sweatshirt","browns coach crewneck","cleveland coach gift"], theme="player"),
"limited-edition-br15": dict(name="Browns Flacco 15 Cleveland Sweatshirt", art="BROWNS FLACCO 15 CLEVELAND", kw=["flacco sweatshirt","browns 15 crewneck","cleveland qb sweatshirt"], theme="player"),
"winter-hat-beanie-flacco": dict(name="Flacco Orange Winter Beanie", art="FLACCO knit beanie", kw=["flacco beanie","browns winter hat","joe flacco hat"], theme="player", type="Beanie"),
"winter-hat-beanie-stefanski": dict(name="Stefanski Orange Winter Beanie", art="STEFANSKI knit beanie", kw=["stefanski beanie","browns coach hat","cleveland winter hat"], theme="player", type="Beanie"),
"winter-hat-beanie-cleveland": dict(name="Cleveland Black Winter Beanie", art="CLEVELAND knit beanie", kw=["cleveland beanie","black winter hat cleveland","ohio knit hat"], theme="city", type="Beanie"),
"winter-hat-beanie-browns": dict(name="Browns Orange Winter Beanie", art="BROWNS knit beanie", kw=["browns beanie","orange winter hat","cleveland knit cap"], theme="classic", type="Beanie"),
"limited-edition-n36": dict(name="Who Needs Coffee Cup Of Joe Flacco Hoodie", art="WHO NEEDS COFFEE WHEN YOU HAVE A CUP OF JOE FLACCO", kw=["cup of joe flacco","funny flacco hoodie","browns coffee shirt"], theme="funny"),
"limited-edition-24n15": dict(name="I'm Joe Doing Joe Things Sweatshirt", art="I'M JOE DOING JOE THINGS", kw=["joe flacco sweatshirt","joe things shirt","browns crewneck"], theme="player"),
"limited-edition-2024n3": dict(name="The Dawgfather Stefanski Sweatshirt", art="THE DAWGFATHER - Stefanski tuxedo portrait", kw=["dawgfather shirt","stefanski sweatshirt","browns godfather tee"], theme="funny"),
"limited-edition-2024n2": dict(name="Dawg Life Bulldog Sweatshirt", art="DAWG LIFE with bulldog", kw=["dawg life shirt","cleveland bulldog sweatshirt","dawg pound crewneck"], theme="classic"),
"limited-edition-241": dict(name="Cleveland Skyline Football Shirt", art="CLEVELAND skyline inside a football", kw=["cleveland skyline shirt","cleveland football tee","ohio skyline shirt"], theme="city"),
"limited-mug-2024": dict(name="Stefanski King Crown Coffee Mug", art="Coach Stefanski wearing a crown", kw=["browns coffee mug","stefanski mug","cleveland gift mug"], theme="funny", type="Mug"),
"limited-edition-2024": dict(name="Stefanski King Crown Hoodie", art="Coach Stefanski wearing a crown", kw=["stefanski hoodie","browns coach hoodie","cleveland king hoodie"], theme="funny"),
"limited-edition-our-coach": dict(name="Our Coach Is Hotter Than Yours Sweatshirt", art="OUR COACH IS HOTTER THAN YOURS", kw=["funny coach shirt","browns coach sweatshirt","cleveland funny crewneck"], theme="funny"),
"limited-edition-66": dict(name="CLVLAND Find A Way By Any Means Sweatshirt", art="CLVLAND - FIND A WAY BY ANY MEANS with skull and bones", kw=["cleveland sweatshirt","find a way shirt","browns bones crewneck"], theme="city"),
"limited-edition-s-u-n-d-a-y-s": dict(name="Sundays Are For The Browns Sweatshirt", art="SUNDAYS ARE FOR THE BROWNS with bulldog", kw=["sundays are for the browns","cleveland sunday shirt","browns crewneck"], theme="classic"),
"limited-edition-d-w-a-g-s": dict(name="Sundays Are For The Dawgs Red Sweatshirt", art="SUNDAYS ARE FOR THE DAWGS with bulldog", kw=["sundays are for the dawgs","dawg pound sweatshirt","cleveland red crewneck"], theme="classic"),
"cleveland-cle": dict(name="CLE Script Football White Sweatshirt", art="Cle script with football lacing", kw=["cle sweatshirt","cleveland script crewneck","minimal cleveland shirt"], theme="city"),
"cleveland-cle-for-fans": dict(name="CLE Script Football Red Sweatshirt", art="Cle script with football lacing", kw=["cle red sweatshirt","cleveland fan crewneck","cle script shirt"], theme="city"),
"limited-edition-b-e-k-i-n-d": dict(name="Be Kind Cleveland Elf Sweatshirt", art="BE KIND with retro Cleveland elf mascot and hearts", kw=["be kind shirt","cleveland elf sweatshirt","retro cleveland crewneck"], theme="retro"),
"limited-edition-d-w-a-g": dict(name="Dawg Pound Bulldog Red Sweatshirt", art="DAWG POUND with bulldog", kw=["dawg pound sweatshirt","cleveland bulldog crewneck","browns red sweatshirt"], theme="classic"),
"limited-edition-b-r-o-w-n-s-h-e-l-m-e-t": dict(name="Cleveland Helmet Phone Case", art="Cleveland helmet on orange and black splatter", kw=["cleveland phone case","browns iphone case","football phone case"], theme="classic", type="Phone Case"),
"cleveland-victory-monday-mug": dict(name="Victory Monday Cleveland Coffee Mug", art="VICTORY MONDAY CLEVELAND with football sunrise", kw=["victory monday mug","cleveland coffee mug","browns mug gift"], theme="city", type="Mug"),
"limited-edition-victory-monday": dict(name="Victory Monday Red Sweatshirt", art="VICTORY MONDAY", kw=["victory monday shirt","cleveland monday crewneck","browns win sweatshirt"], theme="city"),
"limited-edition-b-r-o-w-n-s": dict(name="Refuse To Surrender Winning Is Coming Sweatshirt", art="REFUSE TO SURRENDER - WINNING IS COMING with armored bulldog", kw=["winning is coming shirt","cleveland banner sweatshirt","dawg pound crewneck"], theme="classic"),
"limited-edition-c-l-e-aint-for-sissies": dict(name="Cleveland Ain't For Sissies Sweatshirt", art="CLEVELAND AIN'T FOR SISSIES", kw=["cleveland aint for sissies","tough cleveland shirt","ohio pride sweatshirt"], theme="city"),
"rise-and-shine-it-s-game-day": dict(name="Rise And Shine It's Game Day Sweatshirt", art="RISE AND SHINE IT'S GAME DAY with helmet", kw=["game day sweatshirt","rise and shine football","cleveland gameday crewneck"], theme="classic"),
"limited-edition-cleveland-lovers": dict(name="I'll Always Be Your Biggest Fan Sweatshirt", art="I'LL ALWAYS BE YOUR BIGGEST FAN with player and hearts", kw=["football girlfriend shirt","biggest fan sweatshirt","cleveland womens crewneck"], theme="family"),
"limited-edition-b-r-o-w-n-s-cleveland-case": dict(name="Cleveland Helmet Splatter Phone Case", art="Cleveland helmet on orange splatter", kw=["browns phone case","cleveland iphone case","football case gift"], theme="classic", type="Phone Case"),
"limited-edition-b-r-o-w-n-s1": dict(name="Cleveland Helmet Flag Phone Case", art="Cleveland helmet on orange and black American flag", kw=["cleveland flag phone case","browns case","football phone case"], theme="classic", type="Phone Case"),
"limited-edition-cleveland-fans": dict(name="Stomping On These Haters Browns Style Sweatshirt", art="STOMPING ON THESE HATERS - BROWNS STYLE with sneaker", kw=["stomping on haters shirt","browns sneaker sweatshirt","cleveland hater crewneck"], theme="funny"),
"limited-edition-cleveland": dict(name="Cleveland Bulldog Red Sweatshirt", art="CLEVELAND with angry bulldog", kw=["cleveland bulldog sweatshirt","dawg pound red crewneck","browns bulldog shirt"], theme="classic"),
"d-a-w-g-b-i-t-c-limited-edition": dict(name="Cleveland Bitcoin Bulldawgs Sweatshirt", art="CLEVELAND BITCOIN BULLDAWGS with bulldog and B logo", kw=["bitcoin football shirt","cleveland crypto sweatshirt","bulldawgs crewneck"], theme="funny"),
"i-love-b-r-o-w-n-s-limited-edition": dict(name="I Love Browns Heart Sweatshirt", art="I (heart) BROWNS", kw=["i love browns shirt","cleveland heart sweatshirt","browns valentine gift"], theme="classic"),
"sundays-are-for-the-dawgs": dict(name="Sundays Are For The Dawgs Est 1946 Shirt", art="SUNDAYS ARE FOR THE DAWGS - EST. 1946 with dog", kw=["sundays are for the dawgs","est 1946 shirt","cleveland dawgs tee"], theme="retro"),
"b-r-o-w-n-s-sugar-skull-halloween-long": dict(name="Cleveland Sugar Skull Halloween All-Over Long Sleeve", art="Sugar skull woman in a Cleveland helmet on orange bandana print", kw=["cleveland halloween shirt","sugar skull football shirt","all over print browns"], theme="halloween"),
"b-r-o-w-n-s-sugar-skull-halloween": dict(name="Cleveland Sugar Skull Halloween All-Over Shirt", art="Sugar skull woman in a Cleveland helmet on orange bandana print", kw=["sugar skull cleveland tee","halloween football shirt","all over print shirt"], theme="halloween"),
"cleveland-retro-vintage-classic-ohio-fans-shirt": dict(name="Cleveland Retro Skyline Football Shirt", art="CLEVELAND with skyline football", kw=["retro cleveland shirt","vintage cleveland tee","ohio football vintage shirt"], theme="retro"),
"cleveland-retro-vintage-classic-ohio-gameday-shirt": dict(name="Cleveland Ohio Retro Bulldog Gameday Shirt", art="CLEVELAND OHIO with vintage bulldog and stripes", kw=["vintage cleveland bulldog","retro ohio shirt","cleveland gameday tee"], theme="retro"),
"cleveland-retro-vintage-classic-ohio-shirt": dict(name="Cleveland Ohio Retro Bulldog Shirt", art="CLEVELAND OHIO with vintage bulldog", kw=["retro cleveland ohio shirt","vintage dawg shirt","classic cleveland tee"], theme="retro"),
"vintage-cleveland": dict(name="Vintage Cleveland Script Hoodie", art="Cleveland retro script", kw=["vintage cleveland hoodie","cleveland script sweatshirt","retro ohio hoodie"], theme="retro"),
"stefanski-browns-coach-t-shirt": dict(name="Stefanski Browns Coach Orange Women's Shirt", art="STEFANSKI coach portrait with headset", kw=["stefanski womens shirt","browns coach tee","cleveland orange shirt"], theme="player"),
"in-stefanski-we-trust": dict(name="In Stefanski We Trust Shirt", art="IN STEFANSKI WE TRUST with all-seeing football", kw=["in stefanski we trust","browns coach shirt","cleveland trust tee"], theme="funny"),
"line-man-dad-football-t-shirt": dict(name="Lineman Dad Football Shirt", art="LINEMAN DAD with helmet and flag", kw=["lineman dad shirt","football dad gift","fathers day football tee"], theme="family"),
"my-life-is-for-football-t-shirt": dict(name="My Life Is For Football Shirt", art="MY LIFE IS FOR FOOTBALL with patriotic player", kw=["football life shirt","american football tee","football lover gift"], theme="family"),
"dibs-on-the-coach-football-funny-football-coach-gifts": dict(name="Dibs On The Coach Funny Football Shirt", art="DIBS ON THE COACH with football", kw=["dibs on the coach shirt","football coach wife gift","funny coach tee"], theme="funny"),
# ---------------- DALLAS ----------------
"doomsday-defense-tee": dict(name="Doomsday Defense Dallas Football Shirt", art="DOOMSDAY DEFENSE with skull in a retro helmet and stars", kw=["doomsday defense shirt","dallas defense tee","vintage cowboys defense shirt"], theme="retro"),
"girly-vintage-texas-pride": dict(name="This Girl Loves Cowboys Women's Shirt", art="THIS GIRL LOVES COWBOYS with football and stars", kw=["this girl loves cowboys","dallas womens shirt","cowboys girlfriend gift"], theme="family"),
"dallas-football-vintage-style-tee": dict(name="Dallas Football Star Lightning Vintage Shirt", art="DALLAS FOOTBALL with star, lightning bolts and football", kw=["dallas football shirt","vintage dallas tee","cowboys star shirt"], theme="retro"),
"dallas-football-vintage-athletic-style-fan-tee": dict(name="Dallas Football 1960 Helmet Vintage Shirt", art="DALLAS FOOTBALL 1960 DALLAS, TEXAS with retro helmet", kw=["dallas 1960 shirt","vintage dallas football tee","texas football shirt"], theme="retro"),
"vintage-country-style-graphic-t-shirt": dict(name="Y'all Can Kiss My Dallas Longhorn Shirt", art="Y'ALL CAN KISS MY DALLAS with longhorn skull", kw=["funny dallas shirt","texas longhorn tee","yall can kiss my dallas"], theme="funny"),
"dallas-flag-tee": dict(name="Dallas American Flag Vertical Shirt", art="DALLAS on a distressed vertical American flag", kw=["dallas flag shirt","patriotic dallas tee","texas american flag shirt"], theme="city"),
"dallas-texas-vintage-athletic-style-t-shirt": dict(name="Dallas 1960 Football Helmet White Shirt", art="DALLAS 1960 FOOTBALL with retro helmet", kw=["dallas white tee","vintage 1960 dallas shirt","texas football helmet shirt"], theme="retro"),
"vintage-texas-pride-athletic-state-graphic-t-shirt": dict(name="Dallas Texas State Flag Pride Shirt", art="DALLAS TEXAS with state outline and Texas flag", kw=["texas pride shirt","dallas state outline tee","texas flag shirt"], theme="city"),
"dallas-texas-vintage-athletic-sports-style-t-shirt": dict(name="Dallas Texas Est 1841 Navy Shirt", art="DALLAS EST. 1841 TEXAS collegiate lettering", kw=["dallas est 1841 shirt","dallas texas tee","collegiate dallas shirt"], theme="retro"),
"dallas-texas-vintage-athletic-sports-style-fan-t-shirt": dict(name="Dallas Texas Est 1841 Grey Shirt", art="DALLAS EST. 1841 TEXAS collegiate lettering", kw=["dallas grey tee","dallas texas vintage shirt","texas athletic shirt"], theme="retro"),
# ---------------- GREEN BAY ----------------
"limited-edition-grb37": dict(name="This Girl Loves The Pack Shirt", art="THIS GIRL LOVES THE PACK with crown and hands", kw=["this girl loves the pack","packers womens shirt","green bay girlfriend gift"], theme="family"),
"limited-edition-grb32": dict(name="Cheese Heart Green Bay Shirt", art="Cheese wedge shaped like a heart", kw=["cheesehead shirt","packers cheese heart tee","wisconsin cheese shirt"], theme="funny"),
"limited-edition-grb31": dict(name="Jordan Love 10 Green Bay Hoodie", art="10 LOVE with player and gold 10", kw=["jordan love hoodie","packers 10 sweatshirt","green bay qb hoodie"], theme="player"),
"limited-edition-grb30": dict(name="Jordan Freaking Love Shirt", art="JORDAN FREAKING LOVE", kw=["jordan love shirt","packers qb tee","green bay love shirt"], theme="player"),
"limited-edition-grb29": dict(name="Pack Is Back Green Bay Shirt", art="PACK IS BACK with gold stripes", kw=["pack is back shirt","packers comeback tee","green bay fan shirt"], theme="classic"),
"limited-edition-grb39": dict(name="Robert Tonyan Green Bay Shirt", art="ROBERT TONYAN with player and signature", kw=["robert tonyan shirt","packers tight end tee","green bay 85 shirt"], theme="player"),
"limited-edition-grb40-1": dict(name="Robert Tonyan 85 Repeat Shirt", art="ROBERT TONYAN 85 repeated name stack", kw=["tonyan 85 shirt","packers 85 tee","green bay player shirt"], theme="player"),
"limited-edition-grb38": dict(name="Tonyan 85 Green Bay Player Shirt", art="ROBERT TONYAN 85 with big number", kw=["tonyan shirt","packers 85 jersey tee","green bay tight end shirt"], theme="player"),
"limited-edition-grb33": dict(name="All You Need Is Love 10 Helmet Shirt", art="ALL YOU NEED IS 10VE with helmet and waves", kw=["all you need is love packers","jordan love 10 shirt","green bay retro tee"], theme="retro"),
"limited-edition-grb36": dict(name="Jordan Love 10 Flag Number Shirt", art="Player with a stars and stripes number 10", kw=["jordan love flag shirt","packers 10 tee","green bay patriotic shirt"], theme="player"),
"limited-edition-grb35": dict(name="Cheese Heart Green Bay Mug", art="Cheese wedge heart on a black mug", kw=["packers mug","cheesehead coffee mug","green bay gift mug"], theme="funny", type="Mug"),
"limited-edition-grb8": dict(name="Green Bay Football Cheesehead Nation Shirt", art="GREEN BAY FOOTBALL - SUNDAYS ARE BETTER IN CHEESEHEAD NATION SINCE 1919 with cheese mascot", kw=["cheesehead nation shirt","green bay 1919 tee","packers mascot shirt"], theme="retro"),
"limited-edition-grb7": dict(name="Green Bay Football Cheese And Beer Shirt", art="GREEN BAY FOOTBALL with cheese mascot holding a beer", kw=["packers beer shirt","cheese and beer tee","funny green bay shirt"], theme="funny"),
"limited-edition-grb27": dict(name="Packers Distressed American Flag Shirt", art="PACKERS on a distressed American flag", kw=["packers flag shirt","green bay patriotic tee","usa packers shirt"], theme="city"),
"limited-edition-grb26": dict(name="Green Bay Packers Football Stars Shirt", art="GREEN BAY PACKERS with football and stars", kw=["green bay packers shirt","packers football tee","gold packers shirt"], theme="classic"),
"limited-edition-grb1-1": dict(name="Green Bay Vs Everyone Shirt", art="GREEN BAY VS EVERYONE with football", kw=["green bay vs everyone","packers vs everybody shirt","green bay attitude tee"], theme="classic"),
"limited-edition-grb24": dict(name="Love 10 Jersey Back Shirt", art="LOVE 10 jersey back with player", kw=["jordan love jersey shirt","packers 10 back tee","green bay jersey shirt"], theme="player"),
"limited-edition-grb16": dict(name="Green Bay WI Football Team Est 1919 Shirt", art="GREEN BAY WI FOOTBALL TEAM EST. 1919 crest", kw=["green bay 1919 shirt","packers crest tee","wisconsin football shirt"], theme="retro"),
"limited-edition-grb15": dict(name="Property Of Green Bay Packers 1919 Shirt", art="PROPERTY OF 1919 GREEN BAY PACKERS", kw=["property of packers shirt","green bay 1919 tee","collegiate packers shirt"], theme="retro"),
"limited-edition-grb25": dict(name="Sunday Funday Wisconsin Outline Shirt", art="SUNDAY FUNDAY inside the Wisconsin state outline", kw=["sunday funday shirt","wisconsin outline tee","packers gameday shirt"], theme="city"),
"limited-edition-grb2": dict(name="The Packers Make Me Drink Shirt", art="THE PACKERS MAKE ME DRINK", kw=["packers make me drink","funny packers shirt","green bay beer tee"], theme="funny"),
"limited-edition-grb3": dict(name="Our Coach Is Hotter Than Your Coach Shirt", art="OUR COACH IS HOTTER THAN YOUR COACH", kw=["funny packers coach shirt","green bay coach tee","packers humor shirt"], theme="funny"),
"limited-edition-grb4": dict(name="Let The 10VE Begin Green Bay Shirt", art="LET THE 10VE BEGIN", kw=["let the love begin packers","jordan love 10 tee","green bay qb shirt"], theme="player"),
"limited-edition-grb5": dict(name="Go Pack Go Stencil Shirt", art="GO PACK GO stencil letters", kw=["go pack go shirt","packers chant tee","green bay yellow shirt"], theme="classic"),
"limited-edition-grb6": dict(name="Sunday Funday Green Bay Script Shirt", art="SUNDAY FUNDAY retro script", kw=["sunday funday packers","green bay script tee","packers gameday shirt"], theme="retro"),
"limited-edition-grb9": dict(name="Wisconsin Home State Shirt", art="HOME inside the Wisconsin state outline", kw=["wisconsin home shirt","green bay state tee","wisconsin pride shirt"], theme="city"),
"limited-edition-grb10": dict(name="Green Bay Touchdown Shirt", art="GREENBAY TOUCHDOWN", kw=["green bay touchdown shirt","packers td tee","green bay gameday shirt"], theme="classic"),
"limited-edition-grb11": dict(name="Jordan Love Is All You Need Shirt", art="JORDAN LOVE IS ALL YOU NEED with player", kw=["jordan love shirt","love is all you need packers","green bay 10 tee"], theme="player"),
"limited-edition-grb12": dict(name="What Would Jordan Do Retro Shirt", art="WHAT WOULD JORDAN DO? retro color letters", kw=["what would jordan do","jordan love retro shirt","packers retro tee"], theme="retro"),
"limited-edition-grb13": dict(name="Packers Retro Stacked Repeat Shirt", art="PACKERS PACKERS PACKERS retro stacked", kw=["retro packers shirt","stacked packers tee","green bay vintage shirt"], theme="retro"),
"limited-edition-grb14": dict(name="Packers Groovy Wavy White Shirt", art="PACKERS PACKERS PACKERS groovy wavy letters", kw=["groovy packers shirt","packers wavy tee","green bay womens shirt"], theme="retro"),
"limited-edition-grb17": dict(name="Green Bay Wisconsin Minimal Shirt", art="Green Bay, Wisconsin with gold bar and football", kw=["green bay wisconsin shirt","minimal packers tee","green bay city shirt"], theme="city"),
"limited-edition-grb18": dict(name="The Future Is Green Packers Shirt", art="THE FUTURE IS GREEN", kw=["future is green shirt","packers future tee","green bay optimism shirt"], theme="classic"),
"limited-edition-grb20": dict(name="Sunday Funday Green Bay Bars Shirt", art="SUNDAY FUNDAY with gold bars", kw=["sunday funday packers shirt","green bay olive tee","packers gameday shirt"], theme="classic"),
# ---------------- MICHIGAN ----------------
"limited-edition-m-9-v3": dict(name="J.J. McCarthy 9 Michigan Shirt", art="Michigan quarterback 9 splash art", kw=["jj mccarthy shirt","michigan 9 tee","go blue quarterback shirt"], theme="player"),
"limited-edition-m-9-v2": dict(name="The Legend Of J.J. McCarthy Women's Shirt", art="THE LEGEND OF J.J. MCCARTHY with player and M", kw=["jj mccarthy womens shirt","michigan legend tee","go blue 9 shirt"], theme="player"),
"limited-edition-m-9-v1": dict(name="McCarthy 9 Michigan Kneel Shirt", art="MCCARTHY 9 kneeling player", kw=["mccarthy 9 shirt","michigan qb tee","go blue shirt"], theme="player"),
"valentine-v2": dict(name="I Love Michigan Heart Shirt", art="I (heart) MICHIGAN", kw=["i love michigan shirt","michigan heart tee","go blue valentine gift"], theme="classic"),
"limited-edition-m-fans-30": dict(name="Go Blue Michigan Player Sweatshirt", art="GO BLUE with player and lightning", kw=["go blue sweatshirt","michigan player crewneck","michigan football sweatshirt"], theme="player"),
"limited-edition-m-fans-n30": dict(name="Michigan Vs Everybody Grey Sweatshirt", art="MICHIGAN -VS- EVERYBODY", kw=["michigan vs everybody","michigan grey crewneck","go blue sweatshirt"], theme="classic"),
"limited-edition-m-fans-n29": dict(name="Michigan Bet Ornate Sweatshirt", art="MICHIGAN BET ornate lettering", kw=["michigan bet shirt","go blue crewneck","michigan football sweatshirt"], theme="classic"),
"limited-edition-m-fans-n28": dict(name="Bet M Michigan Sweatshirt", art="BET M block lettering", kw=["bet michigan shirt","michigan m sweatshirt","go blue tee"], theme="classic"),
"limited-edition-m-fans-n27": dict(name="Michigan Revenge Tour Sweatshirt", art="MICHIGAN REVENGE TOUR", kw=["michigan revenge tour","go blue sweatshirt","michigan rivalry shirt"], theme="classic"),
"limited-edition-m-fans-n26": dict(name="Michigan Bet Block Sweatshirt", art="MICHIGAN BET block lettering", kw=["michigan bet crewneck","go blue shirt","michigan navy sweatshirt"], theme="classic"),
"limited-edition-victory": dict(name="Victory Sunday Michigan Helmet Sweatshirt", art="VICTORY SUNDAY with winged helmet", kw=["michigan helmet sweatshirt","victory sunday shirt","go blue crewneck"], theme="classic"),
"limited-edition-m-fans": dict(name="Michigan Vs Everybody Navy Sweatshirt", art="MICHIGAN -VS- EVERYBODY with M logo", kw=["michigan vs everybody sweatshirt","go blue navy crewneck","michigan football shirt"], theme="classic"),
}

