#!/usr/bin/env python3
"""
Live Drops Page - the customer-facing "Trending Now" page.

Reads data/live_drops.json (generated by marketing/live_engine.py) and
data/trends.json, then returns HTML for /drops/.

This is a public storefront page: it shows real products that the Fan Trend
Index is scoring hot, with a short, human description for each. Nothing here
mentions the machinery - no build commands, no file names, no scoring rules,
no revenue strategy. Those live in the marketing/ workspace, not on the page.
"""
import json, os, html
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

try:
    import landing as _l
    def _title_case_art(art):
        return _l.title_case_art(art)
except Exception:
    def _title_case_art(art):
        a = " ".join(str(art or "").split())
        if a.isupper():
            return a.title()
        return a


def esc(s):
    return html.escape(str(s), quote=True)


def load_drops():
    try:
        with open(ROOT / "data" / "live_drops.json", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {"generated": "unknown", "drops": [], "count": 0, "trends_date": "unknown"}


def load_trends():
    try:
        with open(ROOT / "data" / "trends.json", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {"generated": "unknown", "collections": {}}


def drop_blurb(prod, c):
    """One short, human sentence describing the design. Written around the
    actual artwork line and garment - no headline is ever forced into it."""
    garment = (prod.get("garment") or "tee").lower()
    art = _title_case_art(prod.get("art") or "")
    theme = prod.get("theme") or "classic"
    if theme == "player":
        return (f"A fan tribute drawn for {c['short']} supporters - printed on a "
                f"{garment}, on demand.")
    if theme == "funny":
        return (f"Fan humour that lands from across a tailgate lot - printed on a "
                f"{garment}, on demand.")
    if theme in ("retro", "city", "classic"):
        return (f"A vintage-leaning {c['short']} graphic - printed on a {garment}, "
                f"on demand.")
    if art:
        return (f"Original {c['short']} fan art built around \u201c{art}\u201d - "
                f"printed on a {garment}, on demand.")
    return f"An original {c['short']} fan design - printed on a {garment}, on demand."


def build_drops_cards(drops, model_lookup, collections):
    """Build the product cards. Each card is team, trend, product, price,
    a short human description and one Shop button - nothing else."""
    html_cards = ""
    for d in drops:
        slug = d["slug"]
        prod = model_lookup.get(slug)
        if not prod:
            continue
        ckey = d.get("collection") or prod.get("col")
        c = collections.get(ckey, {})
        short = c.get("short") or d.get("collection_short", "")
        accent = {
            "cleveland-browns": "#C8410B",
            "green-bay-packers": "#1A6B47",
            "dallas-cowboys": "#2C4A72",
            "michigan": "#00274C",
        }.get(ckey, "#111")
        img = prod.get("front", d.get("image", ""))
        url = prod.get("url", f"/shop/{slug}/")
        garment = prod.get("garment", "Tee")
        price = f"${prod['price']:.2f}"
        trend_chip = ('<span class="drop-trend">Trending</span>'
                      if prod.get("trend") == "hot" else "")
        html_cards += f"""
<article class="drop-card reveal" data-col="{esc(ckey)}" style="border-top:3px solid {accent}">
  <div class="drop-head">
    <span class="drop-team" style="background:{accent}22;color:{accent}">{esc(short)}</span>
    {trend_chip}
  </div>
  <a href="{esc(url)}" class="drop-img">
    <img src="{esc(img)}" alt="{esc(prod['name'])}" loading="lazy" width="300" height="360">
  </a>
  <div class="drop-body">
    <span class="meta">{esc(garment)} &middot; {esc(price)}</span>
    <h3><a href="{esc(url)}">{esc(prod['name'])}</a></h3>
    <p class="drop-caption">{esc(drop_blurb(prod, c))}</p>
    <a class="btn block" href="{esc(url)}">Shop This Drop &rarr;</a>
  </div>
</article>
"""
    return html_cards


def page_drops_html(collections, order, model_lookup):
    drops_data = load_drops()
    trends = load_trends()
    # Dead-link guard: only drops whose product page the build actually
    # published may render a card (a stale live_drops.json must never ship a
    # "Shop This Drop" link that 404s).
    drops = [d for d in drops_data.get("drops", []) if d.get("slug") in model_lookup][:24]
    generated = drops_data.get("generated", "today")
    trends_date = drops_data.get("trends_date", trends.get("generated", "today"))

    cards_html = build_drops_cards(drops, model_lookup, collections)

    # How many of these are genuinely tagged hot by the live trend system.
    hot = sum(1 for d in drops if model_lookup[d["slug"]].get("trend") == "hot")

    team_opts = '<option value="all">All teams</option>' + "".join(
        f'<option value="{k}">{esc(collections[k]["short"])}</option>' for k in order)

    body = f"""
<main id="main">
<section class="cbanner compact" style="padding:0">
 <div class="band"><img src="/img/hero-home.jpg?v=5" alt="Trending fan designs" width="2048" height="768" fetchpriority="high"></div>
 <div class="cb-in">
  <span class="eyebrow"><span class="dot"></span> Live &middot; updated {esc(generated)}</span>
  <h1>Today's <span class="accentword">Trending Drops</span></h1>
  <p class="lede">Fresh fan-made designs inspired by the football stories fans are talking about
  right now. Updated regularly as the season moves.</p>
  <div class="btnrow">
   <a class="btn lg" href="/fan-trend-index/">See Fan Trend Index &rarr;</a>
   <a class="btn ghost lg" href="/2026-season/">2026 Season Hub</a>
  </div>
 </div>
</section>

<div class="wrap">
<div class="filterbar" style="margin-top:18px" role="search">
 <div class="frow">
  <input id="dropQ" type="search" placeholder="Search drops - e.g. Sanders, Michigan, Doomsday..." aria-label="Search drops">
  <select id="dropTeam" aria-label="Filter drops by team">{team_opts}</select>
 </div>
 <div class="fmeta"><span id="dropCount">{len(drops)} drops</span><button type="button" class="fclear" id="dropClear">Clear all</button></div>
</div>

<div class="stats" style="margin:22px 0">
  <div class="stat"><b>{len(drops)}</b><span>Live Drops</span></div>
  <div class="stat"><b>{hot}</b><span>Trending Now</span></div>
  <div class="stat"><b>{len(order)}</b><span>Team Voices</span></div>
  <div class="stat"><b>Updated {esc(generated)}</b><span>From real team news</span></div>
</div>

<h2 style="margin:28px 0 12px">Live Drops &mdash; {esc(generated)}</h2>
<div class="grid" id="dropsGrid" style="grid-template-columns:repeat(auto-fill,minmax(280px,1fr))">
{cards_html}
</div>

<div class="prose" style="margin:32px 0 40px">
  <h2>How we pick the drops</h2>
  <p>We watch the week's football headlines for Cleveland, Green Bay, Dallas and Michigan, and
  surface the fan-made designs those stories are pushing. When a name or a storyline is everywhere,
  the matching design shows up here. Everything on this page is original, independent fan art -
  printed on demand and shipped worldwide.</p>
</div>

</div>
</main>

<style>
.drop-card{{background:#fff;border:1px solid var(--line);border-radius:16px;overflow:hidden;display:flex;flex-direction:column}}
.drop-head{{padding:10px 14px;display:flex;gap:8px;align-items:center;font-size:.8rem;border-bottom:1px solid var(--line)}}
.drop-team{{padding:3px 10px;border-radius:999px;font-weight:800;letter-spacing:.04em;font-size:.72rem}}
.drop-trend{{margin-left:auto;padding:3px 10px;border-radius:999px;font-weight:800;letter-spacing:.04em;
  font-size:.72rem;background:#fff3e0;color:#b45309}}
.drop-img{{display:block;aspect-ratio:4/5;background:#f6f6f6}}
.drop-img img{{width:100%;height:100%;object-fit:cover}}
.drop-body{{padding:14px;display:flex;flex-direction:column;gap:8px;flex:1}}
.drop-body h3{{font-size:1.02rem;margin:0;line-height:1.25}}
.drop-body h3 a{{color:var(--ink);text-decoration:none}}
.drop-caption{{font-size:.9rem;line-height:1.4;color:var(--ink);margin:0}}
.drop-body .btn{{margin-top:auto}}
</style>

<script>
(function(){{
  var grid=document.getElementById('dropsGrid');
  var sel=document.getElementById('dropTeam');
  var q=document.getElementById('dropQ');
  var count=document.getElementById('dropCount');
  var clear=document.getElementById('dropClear');
  if(!grid||!sel)return;
  var cards=[].slice.call(grid.children);
  function apply(){{
    var filter=sel.value||'all';
    var term=(q&&q.value||'').toLowerCase().trim(), n=0;
    cards.forEach(function(c){{
      var col=c.getAttribute('data-col')||'';
      var txt=c.textContent.toLowerCase();
      var ok=(filter==='all'||col===filter)&&(!term||txt.indexOf(term)>-1);
      c.style.display=ok?'':'none'; if(ok)n++;
    }});
    if(count)count.textContent=n+' drop'+(n===1?'':'s');
  }}
  sel.addEventListener('change',apply);
  if(q)q.addEventListener('input',apply);
  if(clear)clear.addEventListener('click',function(){{
    sel.value='all'; if(q)q.value=''; apply(); if(q)q.focus();
  }});
  apply();
}})();
</script>
"""
    return body
